version: "3.3"

services:
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:1111
    volumes:
      - .:/code
    ports:
      - "1111:1111"
    depends_on:
      - redis-server