version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis_db

    networks:
      - doki_chat_network

    restart: always

  django:
    build: .
    container_name: doki_django

    ports:
    - "1111:1111"

    volumes:
      - .:/DokiDoki

    networks:
      - doki_chat_network
    depends_on:
      - redis

    restart: always

networks:
  doki_chat_network:
    external: true
