# Generated by Django 3.2.8 on 2021-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(default='251d58ca6819fe321f67d1f455d46157deb9cb6f86c935489071fa8be368bd15', max_length=64),
        ),
    ]
