# Generated by Django 3.2.8 on 2021-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0002_alter_user_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(default='expired', max_length=64),
        ),
    ]
