# Generated by Django 3.2.8 on 2021-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0003_alter_user_reset_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure'), ('P', 'Prefer not to say')], default='P', max_length=1),
        ),
    ]
