# Generated by Django 3.2.8 on 2021-11-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='expertise_tags',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
