# Generated by Django 3.2.8 on 2021-11-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(default='general', max_length=128),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_degree_photo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='office_location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_records',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
    ]
