# Generated by Django 3.2.8 on 2021-11-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0007_alter_patientprofile_medical_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_records',
            field=models.TextField(default='nothing yet', null=True),
        ),
    ]
