# Generated by Django 3.2.9 on 2021-11-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0008_alter_patientprofile_medical_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='expertise_tags',
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DokiApp.doctorprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DokiApp.tag')),
            ],
        ),
    ]
