# Generated by Django 3.2.9 on 2022-01-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0014_message_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='user',
            new_name='creator',
        ),
    ]
