# Generated by Django 3.2.9 on 2022-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokiApp', '0015_rename_user_reserve_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(),
        ),
    ]
